version: '3.7'

services:
  backend:
    build: ./simple-api
    ports:
      - "8080:8080"
    container_name: my-api
    networks:
      - my-network
    depends_on:
      - database

  database:
    build: ./database
    ports:
      - "5432:5432"
    container_name: my-db
    networks:
      - my-network
    volumes:
      - db-volume:/var/lib/postgresql/data

  httpd:
    build: ./http-server
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend

  front:
    build: ./devops-front
    ports:
      - "90:90"
    networks :
      - my-network

volumes:
  db-volume:

networks:
  my-network: