- name: Run Proxy
  community.docker.docker_container:
    name: httpd
    image: wandrilledioubate/tp-devops-httpd:latest
    pull: always
    ports:
      - "80:80"
    networks:
      - name: my-network
    state: started