- name: Run Frontend Application
  community.docker.docker_container:
    name: front
    image: wandrilledioubate/tp-devops-httpd:latest
    pull: always
    ports:
      - "90:90"
    env:
      VUE_APP_API_URL: "http://httpd/api"
    networks:
      - name: my-network
    state: started