- hosts: all
  gather_facts: true
  become: true

  roles:
    - cleanup_containers
    - install_docker
    - create_network
    - create_volumes
    - launch_database
    - launch_app
    - launch_proxy
    - launch_frontend