name: CI devops 2024 - Build and Push Docker Images

on:
  workflow_run:
    workflows: ["CI devops 2024 - Test Backend"]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    # Aucune dépendance ici car le workflow lui-même est déclenché après le premier workflow.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # Étape 1 : Connexion à DockerHub
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 2 : Construction et push de l'image backend
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: true

      # Étape 3 : Construction et push de l'image database
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: true

      # Étape 4 : Construction et push de l'image httpd
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./httpd
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: true
